[applet-window-title6]
src.github = "dhruv8sh/plasma6-window-title-applet"
fetch.github = "dhruv8sh/plasma6-window-title-applet"

[fcitx5-pinyin-moegirl]
src.github = "outloudvi/mw2fcitx"
fetch.url = "https://github.com/outloudvi/mw2fcitx/releases/download/$ver/moegirl.dict"

[fcitx5-pinyin-zhwiki]
src.archpkg = "fcitx5-pinyin-zhwiki"
src.prefix = "0.3.0."
fetch.url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.3.0/zhwiki-$ver.dict"

[moviepilot-core]
src.github_tag = "jxxghp/MoviePilot"
src.include_regex = "^v2.[0-9.]+$"
fetch.github = "jxxghp/MoviePilot"

[moviepilot-frontend]
src.github_tag = "jxxghp/MoviePilot-Frontend"
src.include_regex = "^v2.[0-9.]+$"
fetch.github = "jxxghp/MoviePilot-Frontend"

[moviepilot-plugins]
src.git = "https://github.com/jxxghp/MoviePilot-Plugins"
fetch.github = "jxxghp/MoviePilot-Plugins"

[moviepilot-resources]
src.git = "https://github.com/jxxghp/MoviePilot-Resources"
fetch.github = "jxxghp/MoviePilot-Resources"

[sierra-breeze-enhanced-git]
src.git = "https://github.com/kupiqu/SierraBreezeEnhanced"
fetch.github = "kupiqu/SierraBreezeEnhanced"

[teamspeak-management-tools]
src.github = "KunoiSayami/teamspeak-management-tools.rs"
fetch.github = "KunoiSayami/teamspeak-management-tools.rs"
